package interfaz;


import javax.swing.JOptionPane;
import zoo.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sergio
 */
public class addEspecialidad extends javax.swing.JFrame {

    /**
     * Creates new form addEspecialidad
     */
    public addEspecialidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        addEspecialidad = new javax.swing.JLabel();
        JLSalarioMedio = new javax.swing.JLabel();
        jTFNombreEsp = new javax.swing.JTextField();
        JLNombreEsp = new javax.swing.JLabel();
        jSpinnerSalarioMedioEsp = new javax.swing.JSpinner();
        JLNombre1 = new javax.swing.JLabel();
        jSpinnerNPeligrosidad = new javax.swing.JSpinner();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 35, 0, 35, 0};
        jPanel1Layout.rowHeights = new int[] {0, 32, 0, 32, 0, 32, 0, 32, 0};
        jPanel1.setLayout(jPanel1Layout);

        addEspecialidad.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        addEspecialidad.setForeground(new java.awt.Color(51, 51, 51));
        addEspecialidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addEspecialidad.setText("Añadir Especialidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPanel1.add(addEspecialidad, gridBagConstraints);

        JLSalarioMedio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        JLSalarioMedio.setForeground(new java.awt.Color(51, 51, 51));
        JLSalarioMedio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLSalarioMedio.setText("Salario Medio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel1.add(JLSalarioMedio, gridBagConstraints);

        jTFNombreEsp.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jTFNombreEsp, gridBagConstraints);

        JLNombreEsp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        JLNombreEsp.setForeground(new java.awt.Color(51, 51, 51));
        JLNombreEsp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLNombreEsp.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(JLNombreEsp, gridBagConstraints);

        jSpinnerSalarioMedioEsp.setPreferredSize(new java.awt.Dimension(100, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jSpinnerSalarioMedioEsp, gridBagConstraints);

        JLNombre1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        JLNombre1.setForeground(new java.awt.Color(51, 51, 51));
        JLNombre1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLNombre1.setText("Nivel Peligrosidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel1.add(JLNombre1, gridBagConstraints);

        jSpinnerNPeligrosidad.setPreferredSize(new java.awt.Dimension(100, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel1.add(jSpinnerNPeligrosidad, gridBagConstraints);

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/14_Add-512.png"))); // NOI18N
        jButtonAdd.setText("Añadir");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        jPanel1.add(jButtonAdd, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String nombre = jTFNombreEsp.getText();
        float nPeligr = (float) jSpinnerNPeligrosidad.getValue();
        float salario = (float) jSpinnerSalarioMedioEsp.getValue();
        if(nombre.equals("")){
            JOptionPane.showInputDialog(null, "Introduce el nombre");
        }
        else{
            Especialidad esp = new Especialidad (nombre,salario,nPeligr);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEspecialidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLNombre1;
    private javax.swing.JLabel JLNombreEsp;
    private javax.swing.JLabel JLSalarioMedio;
    private javax.swing.JLabel addEspecialidad;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerNPeligrosidad;
    private javax.swing.JSpinner jSpinnerSalarioMedioEsp;
    private javax.swing.JTextField jTFNombreEsp;
    // End of variables declaration//GEN-END:variables
}
